// _react-legacy/src/app/components/AddressSelectScreen.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router';
import { ArrowLeft, Home, Briefcase, Plus } from 'lucide-react';

interface Address {
  id: string;
  label: string;
  icon: 'home' | 'work' | 'other';
  street: string;
  complement: string;
  zipAndDistrict: string;
}

export function AddressSelectScreen() {
  const navigate = useNavigate();
  
  const [addresses] = useState<Address[]>([
    {
      id: '1',
      label: 'Casa',
      icon: 'home',
      street: 'Rua das Flores, 123',
      complement: 'Apto 45, Bloco B',
      zipAndDistrict: '01234-567 • Jardim Primavera'
    },
    {
      id: '2',
      label: 'Trabalho',
      icon: 'work',
      street: 'Av. Paulista, 1000',
      complement: 'Sala 1501, 15º andar',
      zipAndDistrict: '01310-100 • Bela Vista'
    }
  ]);

  const [selectedAddressId, setSelectedAddressId] = useState('1');

  const getIcon = (type: 'home' | 'work' | 'other') => {
    if (type === 'home') return <Home className="w-6 h-6" style={{ color: '#F97316' }} />;
    if (type === 'work') return <Briefcase className="w-6 h-6" style={{ color: '#F97316' }} />;
    return <Home className="w-6 h-6" style={{ color: '#F97316' }} />;
  };

  return (
    <div className="w-full min-h-screen flex flex-col" style={{ backgroundColor: '#FFF7ED' }}>
      <div className="w-full max-w-md mx-auto flex flex-col min-h-screen">
        {/* Header */}
        <div className="flex items-center gap-4 px-6 pt-12 pb-4">
          <button
            onClick={() => navigate('/cart')}
            className="p-2 rounded-full active:bg-black/5 transition-colors"
            aria-label="Voltar"
          >
            <ArrowLeft className="w-6 h-6" style={{ color: '#7C2D12' }} />
          </button>
          <h1 className="text-xl font-bold" style={{ color: '#7C2D12' }}>
            Endereço de entrega
          </h1>
        </div>

        {/* Address List */}
        <div className="flex-1 px-6 mt-4 pb-32 overflow-y-auto" style={{ scrollbarWidth: 'none', msOverflowStyle: 'none' }}>
          {addresses.map((address) => {
            const isSelected = selectedAddressId === address.id;
            
            return (
              <button
                key={address.id}
                onClick={() => setSelectedAddressId(address.id)}
                className="w-full bg-white rounded-xl p-4 mb-3 flex items-start gap-4 transition-all active:scale-[0.98]"
                style={{
                  border: isSelected ? '2px solid #F97316' : '2px solid transparent',
                  backgroundColor: isSelected ? '#FFF7ED' : '#FFFFFF',
                  boxShadow: '0 1px 3px rgba(0, 0, 0, 0.06)'
                }}
              >
                {/* Icon */}
                <div
                  className="w-12 h-12 rounded-full flex items-center justify-center flex-shrink-0"
                  style={{ backgroundColor: '#FFF7ED' }}
                >
                  {getIcon(address.icon)}
                </div>

                {/* Info */}
                <div className="flex-1 text-left">
                  <h3 className="text-base font-bold" style={{ color: '#7C2D12' }}>
                    {address.label}
                  </h3>
                  <p className="text-sm mt-1" style={{ color: '#9A3412' }}>
                    {address.street}
                  </p>
                  <p className="text-sm" style={{ color: '#9A3412' }}>
                    {address.complement}
                  </p>
                  <p className="text-xs mt-1" style={{ color: '#9A3412' }}>
                    {address.zipAndDistrict}
                  </p>
                </div>

                {/* Radio */}
                <div className="flex items-center justify-center w-6 h-6 flex-shrink-0 mt-1">
                  {isSelected ? (
                    <div
                      className="w-6 h-6 rounded-full flex items-center justify-center"
                      style={{ backgroundColor: '#F97316' }}
                    >
                      <div className="w-2 h-2 rounded-full bg-white" />
                    </div>
                  ) : (
                    <div
                      className="w-6 h-6 rounded-full"
                      style={{ border: '2px solid #FED7AA' }}
                    />
                  )}
                </div>
              </button>
            );
          })}

          {/* Add New Address Button */}
          <button
            onClick={() => navigate('/add-address')}
            className="w-full h-14 rounded-xl flex items-center justify-center gap-2 mt-4 active:scale-[0.98] transition-transform"
            style={{
              border: '2px dashed #F97316'
            }}
          >
            <Plus className="w-5 h-5" style={{ color: '#F97316' }} />
            <span className="font-medium" style={{ color: '#F97316' }}>
              Adicionar novo endereço
            </span>
          </button>
        </div>

        {/* Footer */}
        <div
          className="fixed bottom-0 left-0 right-0 bg-white p-6"
          style={{
            borderTop: '1px solid #FED7AA',
            maxWidth: '448px',
            margin: '0 auto'
          }}
        >
          <button
            onClick={() => navigate('/checkout')}
            className="w-full h-14 rounded-2xl font-bold text-lg text-white active:scale-[0.98] transition-transform"
            style={{
              backgroundColor: '#F97316',
              boxShadow: '0 4px 12px rgba(249, 115, 22, 0.3)'
            }}
          >
            Confirmar endereço
          </button>
        </div>
      </div>
    </div>
  );
}

// src/app/pages/address-select-screen.component.ts
﻿import { Component, OnInit, inject } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { LucideArrowLeft, LucideBriefcase, LucideHome, LucidePlus } from '@lucide/angular';
import { AddressService } from '../services/address.service';
import {
  ReturnRoute,
  getReturnPath,
  navigateWithReturn,
  parseReturnRoute,
} from '../utils/navigation.util';

@Component({
  selector: 'app-address-select-screen',
  standalone: true,
  imports: [LucideArrowLeft, LucideHome, LucideBriefcase, LucidePlus],
  template: `
    <div class="w-full min-h-screen flex flex-col" style="background-color: var(--gd-bg)">
      <div class="w-full max-w-md mx-auto flex flex-col min-h-screen">
        <div class="flex items-center gap-4 px-6 pt-12 pb-4">
          <button
            type="button"
            class="p-2 rounded-full active:bg-black/5 transition-colors"
            aria-label="Voltar"
            (click)="goBack()"
          >
            <svg lucideArrowLeft class="w-6 h-6" style="color: var(--gd-text)"></svg>
          </button>
          <h1 class="text-xl font-bold" style="color: var(--gd-text)">{{ pageTitle }}</h1>
        </div>
        <div
          class="flex-1 px-6 mt-4 overflow-y-auto"
          [class.pb-32]="showConfirmButton"
          [class.pb-8]="!showConfirmButton"
          style="scrollbar-width: none; -ms-overflow-style: none"
        >
          @for (address of addressService.addresses(); track address.id) {
            <button
              type="button"
              class="w-full bg-gd-surface rounded-xl p-4 mb-3 flex items-start gap-4 transition-all active:scale-[0.98]"
              [style.border]="
                selectedAddressId === address.id ? '2px solid var(--gd-accent)' : '2px solid transparent'
              "
              [style.backgroundColor]="selectedAddressId === address.id ? 'var(--gd-bg)' : 'var(--gd-surface)'"
              style="box-shadow: 0 1px 3px rgba(0, 0, 0, 0.06)"
              (click)="selectAddress(address.id)"
            >
              <div
                class="w-12 h-12 rounded-full flex items-center justify-center flex-shrink-0"
                style="background-color: var(--gd-bg)"
              >
                @if (address.icon === 'home') {
                  <svg lucideHome class="w-6 h-6" style="color: var(--gd-accent)"></svg>
                } @else if (address.icon === 'work') {
                  <svg lucideBriefcase class="w-6 h-6" style="color: var(--gd-accent)"></svg>
                } @else {
                  <svg lucideHome class="w-6 h-6" style="color: var(--gd-accent)"></svg>
                }
              </div>
              <div class="flex-1 text-left">
                <h3 class="text-base font-bold" style="color: var(--gd-text)">{{ address.label }}</h3>
                <p class="text-sm mt-1" style="color: var(--gd-text-secondary)">{{ address.street }}</p>
                <p class="text-sm" style="color: var(--gd-text-secondary)">{{ address.complement }}</p>
                <p class="text-xs mt-1" style="color: var(--gd-text-secondary)">{{ address.zipAndDistrict }}</p>
              </div>
              <div class="flex items-center justify-center w-6 h-6 flex-shrink-0 mt-1">
                @if (selectedAddressId === address.id) {
                  <div
                    class="w-6 h-6 rounded-full flex items-center justify-center"
                    style="background-color: var(--gd-accent)"
                  >
                    <div class="w-2 h-2 rounded-full bg-gd-surface"></div>
                  </div>
                } @else {
                  <div class="w-6 h-6 rounded-full" style="border: 2px solid var(--gd-border)"></div>
                }
              </div>
            </button>
          }
          <button
            type="button"
            class="w-full h-14 rounded-xl flex items-center justify-center gap-2 mt-4 active:scale-[0.98] transition-transform"
            style="border: 2px dashed var(--gd-accent)"
            (click)="goToAddAddress()"
          >
            <svg lucidePlus class="w-5 h-5" style="color: var(--gd-accent)"></svg>
            <span class="font-medium" style="color: var(--gd-accent)">Adicionar novo endereço</span>
          </button>
        </div>
        @if (showConfirmButton) {
          <div
            class="fixed bottom-0 left-0 right-0 bg-gd-surface p-6"
            style="border-top: 1px solid var(--gd-border); max-width: 448px; margin: 0 auto"
          >
            <button
              type="button"
              class="w-full h-14 rounded-2xl font-bold text-lg text-white active:scale-[0.98] transition-transform"
              style="background-color: var(--gd-accent); box-shadow: 0 4px 12px rgba(249, 115, 22, 0.3)"
              (click)="confirmSelection()"
            >
              {{ confirmButtonLabel }}
            </button>
          </div>
        }
      </div>
    </div>
  `,
})
export class AddressSelectScreenComponent implements OnInit {
  private route = inject(ActivatedRoute);
  router = inject(Router);
  addressService = inject(AddressService);

  returnTo: ReturnRoute = 'cart';
  selectedAddressId = '';

  get isProfileMode(): boolean {
    return this.returnTo === 'profile';
  }

  get pageTitle(): string {
    return this.isProfileMode ? 'Endereços salvos' : 'Endereço de entrega';
  }

  get showConfirmButton(): boolean {
    return !this.isProfileMode;
  }

  get confirmButtonLabel(): string {
    return this.returnTo === 'checkout' ? 'Usar este endereço' : 'Confirmar endereço';
  }

  ngOnInit(): void {
    this.returnTo = parseReturnRoute(this.route, 'cart');
    this.selectedAddressId = this.addressService.selectedAddressId();
  }

  selectAddress(id: string): void {
    this.selectedAddressId = id;
    this.addressService.selectAddress(id);
  }

  goBack(): void {
    this.router.navigateByUrl(getReturnPath(this.returnTo));
  }

  goToAddAddress(): void {
    navigateWithReturn(this.router, '/add-address', this.returnTo);
  }

  confirmSelection(): void {
    this.addressService.selectAddress(this.selectedAddressId);
    this.router.navigateByUrl('/checkout');
  }
}
