// _react-legacy/src/app/components/ForgotPasswordScreen.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router';
import { ArrowLeft, Mail } from 'lucide-react';

export function ForgotPasswordScreen() {
  const navigate = useNavigate();
  const [email, setEmail] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    // Lógica de recuperação de senha aqui
    console.log('Forgot password:', { email });
    // Redireciona para tela de verificação OTP
    navigate('/otp-verification');
  };

  return (
    <div className="w-full min-h-screen overflow-hidden flex flex-col" style={{ backgroundColor: '#FFF7ED' }}>
      <div className="w-full max-w-md mx-auto flex flex-col min-h-screen">
        {/* Header */}
        <div className="relative flex items-center justify-center px-6 pt-12 pb-6">
          {/* Back Button */}
          <button
            onClick={() => navigate('/login')}
            className="absolute left-6 top-12 p-2 rounded-full active:bg-black/5 transition-colors"
          >
            <ArrowLeft className="w-6 h-6" style={{ color: '#7C2D12' }} />
          </button>

        {/* Logo */}
        <div className="flex flex-col items-center">
          <svg 
            width="48" 
            height="48" 
            viewBox="0 0 64 64" 
            fill="none" 
            xmlns="http://www.w3.org/2000/svg"
            className="mb-2"
          >
            <path 
              d="M8 20C8 20 12 12 32 12C52 12 56 20 56 20C56 20 56 24 56 26C56 28 54 28 54 28H10C10 28 8 28 8 26C8 24 8 20 8 20Z" 
              fill="#F97316"
            />
            <path 
              d="M10 28H54C54 28 54 30 52 32C50 34 48 34 48 34H16C16 34 14 34 12 32C10 30 10 28 10 28Z" 
              fill="#F97316"
              opacity="0.8"
            />
            <rect 
              x="12" 
              y="34" 
              width="40" 
              height="8" 
              rx="2" 
              fill="#F97316"
            />
            <path 
              d="M10 42H54C54 42 56 42 56 44C56 46 54 52 32 52C10 52 8 46 8 44C8 42 10 42 10 42Z" 
              fill="#F97316"
            />
          </svg>
          
          <h1 className="text-2xl font-bold tracking-tight" style={{ color: '#F97316' }}>
            GoDelivery
          </h1>
        </div>
      </div>

        {/* Content Container */}
        <div className="flex-1 flex flex-col px-6 pt-8 pb-8">
        {/* Title */}
        <div className="mb-6">
          <h2 className="text-2xl font-bold mb-3" style={{ color: '#7C2D12' }}>
            Recuperar senha
          </h2>
          <p className="text-sm leading-relaxed" style={{ color: '#9A3412' }}>
            Digite seu e-mail para receber as instruções de redefinição de senha.
          </p>
        </div>

        {/* Form */}
        <form onSubmit={handleSubmit} className="flex flex-col gap-6">
          {/* Email Field */}
          <div className="relative">
            <div className="absolute left-4 top-1/2 -translate-y-1/2 z-10">
              <Mail className="w-5 h-5" style={{ color: '#F97316' }} />
            </div>
            <input
              type="email"
              placeholder="E-mail"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="w-full h-14 pl-12 pr-4 bg-white rounded-xl border-2 transition-all outline-none focus:border-opacity-100"
              style={{ 
                borderColor: '#FED7AA',
                boxShadow: '0 2px 8px rgba(0, 0, 0, 0.04)'
              }}
              required
            />
          </div>

          {/* Submit Button */}
          <button
            type="submit"
            className="w-full h-14 rounded-2xl font-bold text-white text-lg transition-all active:scale-98"
            style={{ 
              backgroundColor: '#F97316',
              boxShadow: '0 4px 12px rgba(249, 115, 22, 0.3)'
            }}
          >
            Enviar instruções
          </button>

          {/* Back to Login Link */}
          <div className="text-center mt-2">
            <span className="text-sm" style={{ color: '#7C2D12' }}>
              Lembrou sua senha?{' '}
              <button
                type="button"
                onClick={() => navigate('/login')}
                className="font-bold"
                style={{ color: '#EA580C' }}
              >
                Entrar
              </button>
            </span>
          </div>
        </form>
        </div>
      </div>
    </div>
  );
}

// src/app/pages/forgot-password-screen.component.ts
﻿import { Component, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { LucideArrowLeft, LucideMail } from '@lucide/angular';
import { GoLogoComponent } from '../shared/go-logo.component';
import { FirebaseService } from '../services/firebase.service';

@Component({
  selector: 'app-forgot-password-screen',
  standalone: true,
  imports: [FormsModule, LucideArrowLeft, LucideMail, GoLogoComponent],
  template: `
    <div class="w-full min-h-screen overflow-hidden flex flex-col" style="background-color: var(--gd-bg)">
      <div class="w-full max-w-md mx-auto flex flex-col min-h-screen">
        <div class="relative flex items-center justify-center px-6 pt-12 pb-6">
          <button
            type="button"
            (click)="router.navigateByUrl('/login')"
            class="absolute left-6 top-12 p-2 rounded-full active:bg-black/5 transition-colors"
          >
            <svg lucideArrowLeft class="w-6 h-6" [style.color]="'var(--gd-text)'"></svg>
          </button>

          <div class="flex flex-col items-center">
            <app-go-logo [size]="48" className="mb-2" />
            <h1 class="text-2xl font-bold tracking-tight" style="color: var(--gd-accent)">GoDelivery</h1>
          </div>
        </div>

        <div class="flex-1 flex flex-col px-6 pt-8 pb-8">
          <div class="mb-6">
            <h2 class="text-2xl font-bold mb-3" style="color: var(--gd-text)">Recuperar senha</h2>
            <p class="text-sm leading-relaxed" style="color: var(--gd-text-secondary)">
              Digite seu e-mail para receber as instruções de redefinição de senha.
            </p>
          </div>

          <form (submit)="handleSubmit($event)" class="flex flex-col gap-6">
            <div class="relative">
              <div class="absolute left-4 top-1/2 -translate-y-1/2 z-10">
                <svg lucideMail class="w-5 h-5" [style.color]="'var(--gd-accent)'"></svg>
              </div>
              <input
                type="email"
                placeholder="E-mail"
                [(ngModel)]="email"
                name="email"
                class="w-full h-14 pl-12 pr-4 bg-gd-surface rounded-xl border-2 transition-all outline-none focus:border-opacity-100"
                style="border-color: var(--gd-border); box-shadow: 0 2px 8px rgba(0, 0, 0, 0.04)"
                required
              />
            </div>

            <button
              type="submit"
              [disabled]="isLoading"
              class="w-full h-14 rounded-2xl font-bold text-white text-lg transition-all active:scale-98 disabled:opacity-70"
              style="background-color: var(--gd-accent); box-shadow: 0 4px 12px rgba(249, 115, 22, 0.3)"
            >
              {{ isLoading ? 'Enviando...' : 'Enviar instruções' }}
            </button>
            @if (message) {
              <p class="text-sm text-center mt-2" style="color: #16A34A">{{ message }}</p>
            }

            <div class="text-center mt-2">
              <span class="text-sm" style="color: var(--gd-text)">
                Lembrou sua senha?
                <button
                  type="button"
                  (click)="router.navigateByUrl('/login')"
                  class="font-bold"
                  style="color: var(--gd-accent-dark)"
                >
                  Entrar
                </button>
              </span>
            </div>
          </form>
        </div>
      </div>
    </div>
  `,
})
export class ForgotPasswordScreenComponent {
  router = inject(Router);
  private firebase = inject(FirebaseService);
  email = '';
  isLoading = false;
  message = '';

  async handleSubmit(event: Event): Promise<void> {
    event.preventDefault();
    this.message = '';
    if (!this.email) return;
    this.isLoading = true;
    try {
      await this.firebase.resetPassword(this.email);
      this.message = 'E-mail de redefinição enviado! Verifique sua caixa de entrada.';
      // Após alguns segundos vai para login (OTP é fluxo demo)
      setTimeout(() => this.router.navigateByUrl('/login'), 2200);
    } catch (e: any) {
      this.message = 'Erro ao enviar. Verifique o e-mail ou tente mais tarde.';
    } finally {
      this.isLoading = false;
    }
  }
}
